import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemesProvider from "@/componets/theme-provider";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Devspace",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-gray-900! dark:text-white!`}
      >
        <ToastContainer
          position="top-center" // Apply globally to all toasts
          autoClose={5000}
          hideProgressBar={true}
          closeOnClick={true}
          progressClassName={undefined}
          closeButton={false}
          pauseOnHover={true}
          draggable={true}
          toastClassName="!rounded-full dark:bg-gray-800 dark:text-white !text-sm !font-bold text-center! text-black" // Global styles for all toasts
        />
        <ThemesProvider>
          <>{children}</>
        </ThemesProvider>
      </body>
    </html>
  );
}
